#!/bin/bash
ROOT_DIR="$HOME/Code/project/chap11"
IP="192.168.52.131"
declare -A service0=(
    [name]='payment_service'
    [port]='3003'
)

declare -A service1=(
    [name]='book_service'
    [port]='3002'
)

declare -A service2=(
    [name]='shipment_service'
    [port]='3004'
)

declare -A service3=(
    [name]='user_service'
    [port]='3001'
)



declare -n service
for service in ${!service@};do 
    echo "$ROOT_DIR/${service[name]}"
    cd $ROOT_DIR/${service[name]}
    python3 manage.py runserver $IP:${service[port]} &
done

cd $ROOT_DIR/client
npm run dev

netstat -plten |grep python3