POST http://192.168.52.131:3001/userregistration/
Content-Type: application/json

{
    "first_name": "Nghia",
    "last_name": "Nguyen",
    "email": "nghia@gmail.com",
    "mobile_number": "0123456789",
    "password": "123",
    "confirm_password": "123",
    "address": "Ha Noi"
}

###
POST http://192.168.52.131:3001/userinfo/
Content-Type: application/json

{
    "username": "nghia@gmail.com"
}

###

POST http://192.168.52.131:3001/userlogin/
Content-Type: application/json

{
    "username": "nghia@gmail.com",
    "password": "123"
}

###
GET http://192.168.52.131:3002/book/list

###
POST http://192.168.52.131:3004/shipment_updates/
Content-Type: application/json

{
    "first_name": "nghia",
    "last_name": "nguyen",
    "email_id": "nghia@gmail.com",
    "mobile_number": "12345",
    "address": "HN",
    "product_id": 1,
    "quantity": 10,
    "payment_status": 1,
    "transaction_id": "111"
}

###
POST http://192.168.52.131:3003/initiate_payment/ 
Content-Type: application/json

{
    "user_name": "nghia@gmail.com",
    "product_id": 1,
    "price": 12,
    "quantity": 3,
    "payment_mode": "visa",
    "mobile_number": "123456"
}


