# Generated by Django 4.1.7 on 2023-04-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='catergories',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
    ]
