# Generated by Django 4.1.7 on 2023-04-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_model', '0002_book_author_book_catergories_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='availability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
    ]
