# Generated by Django 4.1.7 on 2023-04-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='type',
            field=models.CharField(default='book', max_length=100),
        ),
    ]
