# Generated by Django 4.1.7 on 2023-03-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='product_details',
        ),
    ]
